# Generated by Django 3.1.4 on 2020-12-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201207_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='promote',
            field=models.BooleanField(default=False),
        ),
    ]
