# Generated by Django 3.1.4 on 2020-12-12 10:16

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_promote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.FileField(default='files/default.jpg', upload_to='files/article_cover', validators=[blog.models.validate_file_extension]),
        ),
    ]
