# Generated by Django 3.1.4 on 2020-12-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201212_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(default='files/default.jpg', upload_to='files/article_cover'),
        ),
    ]
